site_name: RackioAI Documentation

theme:
  name: material

repo_name: RackioAI
repo_url: https://github.com/crivero7/RackioAI
edit_uri: ""
site_dir: _build/html

nav:
    - Introduction: 'index.md'
    - Install: 'install.md'
    - QuickStart: 'quick_start.md'
    - API Reference:
      - RackioAI: 'api_core.md'
      - Pipeline: 'api_pipeline_core.md'
      - Readers:
        - Reader: 'api_reader_core.md'
        - TPL: 'api_reader_tpl.md'
        - CSV: 'api_reader_csv.md'
        - EXL: 'api_reader_exl.md'
      - Data Analysis:
        - RackioEDA: 'api_data_analysis_core.md'
      - Preprocessing:
        - Preprocessing: 'api_preprocessing_core.md'
        - Synthetic Data: 'api_preprocessing_synthetic_data.md'
        - Kalman Filter: 'api_preprocessing_kalman_filter.md'
        - Scaler: 'api_preprocessing_scaler.md'
        - Splitter: 'api_preprocessing_splitter.md'
      - Models:
        - RackioDNN: 'api_model_RackioDNN.md'
      - Restful API: 'restful_api.md'
      - Utils:
        - decorators: 'decorators.md'
        - Utils: 'api_utils_Utils.md'
      - Managers: 'api_managers_core.md'
    - User Guide: 'user_guide.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

extra_css:
    - css/custom.css