site_name: RackioAI Documentation

theme: readthedocs

repo_name: RackioAI
repo_url: https://github.com/crivero7/RackioAI
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quick_start.md'
    - API Reference: 'api.md'
    - User Guide: 'user_guide.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc