site_name: RackioAI Documentation

theme:
  name: material

repo_name: RackioAI
repo_url: https://github.com/crivero7/RackioAI
edit_uri: ""
site_dir: RackioAI-documentation/_build/html

nav:
    - Introduction: 'index.md'
    - Install: 'install.md'
    - QuickStart: 'quick_start.md'
    - API Reference:
      - RackioAI:
        - core: 'api_core_RackioAI.md'
        - DataHandler: 'api_data_handler_DataHandler.md'
        - Preprocess: 'api_preprocess_Preprocess.md'
        - Data Loaders: 'api_rackio_loader.md'
      - Data Analysis:
        - RackioEDA: 'api_data_analysis_RackioEDA.md'
      - Preprocessing:
        - Synthetic Data: 'api_preprocessing_synthetic_data.md'
    - User Guide: 'user_guide.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

extra_css:
    - css/custom.css